### ISSUE TITLE
@index in function arguments

### ISSUE THREAD

**Issue by JanMP** [dalgard/meteor-jade#1] opened 2015-10-26 14:37 UTC
It would be nice to be able to do this:

```
p #{invalidText "answers.#{@index}.text"}
```

but the string that winds up in invalidText is "answers.{{@index}}.text"

It's easy to work around it since #{someFunction "some string" @index} works fine, but it's really inconvenient (and has a low aesthetic value)

**Comment by dalgard** [comment] 2015-10-26 15:09
Thanks for bringing up this use of `@index`.

The problem is that nested interpolation is neither a feature of Spacebars nor Jade. Your example would look like this in Spacebars:

``` html
<p>{{invalidText "answers.{{@index}}.text"}}</p>
```

That doesn't work.

However, you are trying to pass a key as a string, which is a bit of a code smell to begin with, so if I were you, I would find a way to refactor my data.

**Comment by dalgard** [comment] 2015-10-27 14:31
Feel free to comment again – otherwise, please close the issue. Thanks.

**Comment by JanMP** [comment] 2015-10-27 17:38
This string ist passed into a function from the simple schema package. aldeed/meteor-simple-schema and aldeed/meteor-collection (and probably also aldeed/autoform) seem to use this quite a bit.

**Comment by dalgard** [comment] 2015-10-27 21:08
I can't seem to find the `invalidText` helper in the `aldeed:simple-schema` package. How is the string passed to SimpleSchema?

**Comment by JanMP** [comment] 2015-10-28 09:49
`invalidText(key, index)`is one of my helpers that I used as a workaround to paste the index into the string. So in my template it actually is `p #{invalidText "answers.@.text" @index}` instead of the wished for example above.

That string is then passed to `myValidationContext.keyErrorMessage(key)`

This type of key is used in those packages all over the place to refer to parts of the schemata.

**Comment by dalgard** [comment] 2015-10-28 10:50
I understand. I'm afraid this is a limitation in Blaze/Spacebars that can't be overcome by Jade.

**Closed as completed by dalgard** 2015-10-28 10:50 UTC

**Comment by avalanche1** [comment] 2015-11-23 11:34
Hey guys!
I can't quite grasp the concept behind @index.. Could you provide a simple example for it? Thanks!

**Comment by JanMP** [comment] 2015-11-23 18:04
> Am 23.11.2015 um 12:34 schrieb Artem Saffron notifications@github.com:
> 
> Hey guys!
> I can't quite grasp the concept behind @index https://github.com/index.. Could you provide a simple example for it? Thanks!

template(name=„bookListing“)
  div
    each books
      p #{@index}. #{title}

should yield output:
1. Neuromancer
2. Count Zero
3. Mona Lisa Overdrive

**Comment by avalanche1** [comment] 2015-11-24 19:12
thanks!
